"""empty message

Revision ID: 3d11db0421eb
Revises: c5e1186e1b65
Create Date: 2024-08-15 20:41:34.988940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d11db0421eb'
down_revision = 'c5e1186e1b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
