"""empty message

Revision ID: 667df41d7a6f
Revises: 4dfeb73c1a21
Create Date: 2024-10-13 23:24:52.589156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667df41d7a6f'
down_revision = '4dfeb73c1a21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destacado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('destacado')

    # ### end Alembic commands ###
