"""empty message

Revision ID: 89605597ea08
Revises: 
Create Date: 2024-10-19 23:05:54.359808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89605597ea08'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estado_orden', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
        batch_op.drop_constraint('factura_ibfk_2', type_='foreignkey')
        batch_op.drop_column('total')
        batch_op.drop_column('fecha_emision')
        batch_op.drop_column('proceso_pago_id')

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
        batch_op.drop_column('total')
        batch_op.drop_column('fecha_orden')

    with op.batch_alter_table('proceso_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monto', sa.Integer(), nullable=False))
        batch_op.drop_constraint('proceso_pago_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('proceso_pago_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('proceso_pago_ibfk_4', type_='foreignkey')
        batch_op.drop_column('total')
        batch_op.drop_column('factura_id')
        batch_op.drop_column('tipo_pago')
        batch_op.drop_column('orden_id')
        batch_op.drop_column('estado_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proceso_pago', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('orden_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('tipo_pago', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('factura_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total', mysql.FLOAT(), nullable=False))
        batch_op.create_foreign_key('proceso_pago_ibfk_4', 'factura', ['factura_id'], ['id'])
        batch_op.create_foreign_key('proceso_pago_ibfk_3', 'estado_orden', ['estado_id'], ['id'])
        batch_op.create_foreign_key('proceso_pago_ibfk_1', 'orden', ['orden_id'], ['id'])
        batch_op.drop_column('monto')

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_orden', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('total', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('fecha_creacion')

    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proceso_pago_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_emision', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('total', mysql.FLOAT(), nullable=False))
        batch_op.create_foreign_key('factura_ibfk_2', 'proceso_pago', ['proceso_pago_id'], ['id'])
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('monto')

    with op.batch_alter_table('estado_orden', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
