"""empty message

Revision ID: ada36ee92bda
Revises: 7e65abf31ba7
Create Date: 2024-10-14 23:54:14.004485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada36ee92bda'
down_revision = '7e65abf31ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('direccion', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['direccion'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('direccion')
        batch_op.drop_column('apellido')
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###
