"""empty message

Revision ID: 45565e29462e
Revises: ea1490d5598c
Create Date: 2024-08-19 14:22:48.104931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45565e29462e'
down_revision = 'ea1490d5598c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_column('stock')

    # ### end Alembic commands ###
