"""empty message

Revision ID: 912ab5ec63aa
Revises: 
Create Date: 2024-11-12 15:28:12.193275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '912ab5ec63aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regiones',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('codigo_padre', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provincias',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('region_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comunas',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('provincia_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['provincia_id'], ['provincias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comunas')
    op.drop_table('provincias')
    op.drop_table('regiones')
    # ### end Alembic commands ###
