"""empty message

Revision ID: 69d7216e759b
Revises: 079a18225d06
Create Date: 2024-10-20 20:55:24.539489

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '69d7216e759b'
down_revision = '079a18225d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarjeta', schema=None) as batch_op:
        batch_op.drop_column('saldo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarjeta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saldo', mysql.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
